### ISSUE TITLE
关于小红书的x-sign问题

### ISSUE THREAD

**Issue by SoneyChan7** [haoye999/xiaohongshu-nest#1]
试了一下 X + md5(url+'WSUDD') 和请求到的x-sign不一致, 是换算法了吗

**Comment by haoye999** [comment]
没问题的，注意要加上search参数信息 [相关代码](https://github.com/haoye999/xiaohongshu-nest/blob/dc0c32c77bb2bba49440ae8becb5783ecd209888/src/common/utils/index.ts#L11)

**Comment by haoye999** [comment]
该方法对`/fe_api`开头的接口有效，即web端、微信小程序端部分接口。

**Comment by ideaaaaa** [comment]
您好现在这个算法还对吗，我用了下感觉生成的不对了
